"""first

Revision ID: 5214fb48e7c0
Revises: e27c75ab7eb7
Create Date: 2022-09-26 21:22:58.396819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5214fb48e7c0'
down_revision = 'e27c75ab7eb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_table('favourites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favourites_id'), 'favourites', ['id'], unique=True)
    op.add_column('recipes', sa.Column('dish_type', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'recipes', 'dishtypes', ['dish_type'], ['id'])
    op.drop_column('recipes', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'is_active')
    op.drop_column('recipes', 'dish_type')
    op.drop_index(op.f('ix_favourites_id'), table_name='favourites')
    op.drop_table('favourites')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
